### Pengujian API menggunakan REST Client

GET http://localhost:3000/api/v1/auth/admin


### Login admin
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "",
  "password": ""
}

### Create Admin
POST http://localhost:3000/api/v1/auth/create
Content-Type: application/json

{
  "username": "hirojin",
  "password": "FakesteP#666",
  "email": "xxrabka@gmail.com",
  "name": "Hirooo"
}

### Update Admin
PUT http://localhost:3000/api/v1/auth/1
Content-Type: application/json

{
  "username": "gantengbanget",
  "password": "1234",
  "email": "ganteng1234@gmail.com",
  "name": "Admin User Updated"
}

### Delete Admin
DELETE http://localhost:3000/api/v1/auth/1
Content-Type: application/json
