###
# ================================= #
#       VARIABEL GLOBAL API         #
# ================================= #
@baseUrl = http://localhost:5000/api/v1
@authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBdG1pbiIsInBhc3N3b3JkIjoiJDJiJDEwJEx5ZXJMOFVMTzRUTWdpNkhTZW14QmVhcmRHVFMvaTI2bTFqWEhvZ1h0VGVneXYxQjJRalVHIiwiZW1haWwiOiJFdG1pbkBnbWFpbC5jb20iLCJuYW1lIjoiYXRlbWluIiwiaXNBY3RpdmUiOnRydWUsImNyZWF0ZWRBdCI6IjIwMjUtMDktMjlUMDY6MTQ6NDMuMDY5WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDktMjlUMDY6MTQ6NDMuMDY5WiIsImRlbGV0ZWRBdCI6bnVsbCwiaWF0IjoxNzU5NDk0MjgyLCJleHAiOjE3NTk0OTYwODJ9.jNS2Cwc1_1rB9CflgQ1PQ27h3hB02VU8hP46y2iPJR8
@adminId = 1
@counterId = 1
@queueId = 3


###
# ================================= #
#      FITUR 1: AUTENTIKASI (AUTH)      #
# ================================= #

### [GET] GET semua admin
GET {{baseUrl}}/auth/admins

### [POST] Logout
POST {{baseUrl}}/auth/logout
Authorization: {{authToken}}
Content-Type: application/json

### [POST] Login sebagai Admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "Atmin",
  "password": "Atmin#666"
}

### [POST] Membuat Admin Baru
POST {{baseUrl}}/auth/create
Authorization: {{authToken}}
Content-Type: application/json

{
  "username": "Atmin",
  "password": "Atmin#666",
  "email": "Etmin@gmail.com",
  "name": "atemin"
}

### [PUT] Memperbarui Data Admin
PUT {{baseUrl}}/auth/2
Authorization: {{authToken}}
Content-Type: application/json

{
  "username": "Gans",
  "password": "Gans#123",
  "email": "ganteng1234@gmail.com",
  "name": "Admin User Updated"
}

### [DELETE] Menghapus Admin
DELETE {{baseUrl}}/auth/6
Authorization: {{authToken}}

###
PUT  {{baseUrl}}/auth/1/toggle-status
Authorization: {{authToken}}


###
# ================================= #
#       FITUR 2: LOKET (COUNTERS)      #
# ================================= #

### [GET] Mendapatkan semua loket
GET {{baseUrl}}/counters

### [GET] Mendapatkan loket berdasarkan ID
GET {{baseUrl}}/counters/{{counterId}}

### [POST] Membuat loket baru
POST {{baseUrl}}/counters
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Loket Pendaftaran B",
  "maxQueue": 30
}

### [PUT] Memperbarui loket
PUT {{baseUrl}}/counters/{{counterId}}
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "Loket Pelayanan A (Updated)",
  "maxQueue": 150,
  "isActive": true
}

### [PUT] Memperbarui status loket (aktif/tidak aktif)
PUT {{baseUrl}}/counters/{{counterId}}/status
Content-Type: application/json
Authorization: {{authToken}}

{
  "status": "inactive"
}

### [DELETE] Menghapus loket
DELETE {{baseUrl}}/counters/{{counterId}}
Authorization: {{authToken}}


###
# ================================= #
#       FITUR 3: ANTRIAN (QUEUES)       #
# ================================= #

### [POST] Mengambil Nomor Antrean Baru
POST {{baseUrl}}/queues/claim
Content-Type: application/json

### [GET] Melihat Semua Antrean
GET {{baseUrl}}/queues/current


### [GET] Melihat Semua Antrean
GET {{baseUrl}}/queues/metrics

### [GET] Melihat Antrean Saat Ini di Sebuah Loket
GET {{baseUrl}}/queues/current/{{counterId}}

### [PUT] Panggil Antrean Berikutnya
POST {{baseUrl}}/queues/next/
Authorization: {{authToken}}
Content-Type: application/json

{
  "counter_id": 1
}
### [PUT] Lewati Antrean
PUT {{baseUrl}}/queues/skip/{{counterId}}
Authorization: {{authToken}}

### [PUT] Lepas/Batalkan Antrean Tertentu
PUT {{baseUrl}}/queues/release/6

### [DELETE] Reset Semua Antrean di Sebuah Loket
DELETE {{baseUrl}}/queues/reset/{{counterId}}
Authorization: {{authToken}}